Repository aurora-is-near/eth-connector, pull requests merged in 2022-01, with the labels that each got.

#32 EthCustodian: minor improvements.
  eth-custodian/contracts/EthCustodian.sol
Labels: enhancement

#30 Borsh: check if the decoding is finished
  eth-custodian/contracts/EthCustodian.sol
Labels: bug

#33 README.md: fix typo
  README.md
Labels: documentation
