Repository aurora-is-near/eth-connector, pull requests merged in 2022-03, with the labels that each got.

#40 CI: add SigmaPrime testing suite
  .github/workflows/sigma-prime.yml
Labels: security, devops

#36 Hardhat: add Goerli network
  eth-custodian/hardhat.config.js
Labels: enhancement

#41 EthCustodian: `withdraw` method improvements. Update OZ version.
  eth-custodian/contracts/EthCustodian.sol
  eth-custodian/package.json
  eth-custodian/yarn.lock
Labels: enhancement, security
